name: "Ewon ETK Build Test"
description: "GitHub Action to test build Java projects using the Ewon Java ETK."
author: "alha@hms.se"

inputs:

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "coffee"
  color: "blue"
